batch_mode: true
max_workers: 16
output_dir: eval_results
tests:
- name: framethinker_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: framethinker
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
- name: gaia_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: gaia
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
- name: gta_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: gta
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
- name: toolbench_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: toolbench
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
- name: skywork_doc_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: skywork_doc
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
- name: skywork_excel_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: skywork_excel
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
- name: skywork_normal_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: skywork_normal
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
- name: skywork_ppt_qwen3vl_32b_tool_redundancy_8
  mode: inference_tool_redundancy
  dataset: skywork_ppt
  test_model: qwen3vl-32B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 20000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 8
