batch_mode: true
max_workers: 8
output_dir: eval_results
tests:
- name: framethinker_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: framethinker
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
- name: gaia_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: gaia
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
- name: gta_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: gta
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
- name: toolbench_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: toolbench
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 30
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
- name: skywork_doc_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: skywork_doc
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
- name: skywork_excel_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: skywork_excel
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
- name: skywork_normal_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: skywork_normal
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
- name: skywork_ppt_internvl3_5_30b_tool_redundancy_2_eval
  mode: evaluation_tool_redundancy
  dataset: skywork_ppt
  test_model: internvl3-5-30B
  eval_model: gpt-5
  prediction_file: null
  max_samples: 8
  test_max_tokens: 5000
  eval_max_tokens: 64000
  resume: true
  num_redundant_tools: 2
